
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Icha
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }
    
    public void Tambah(){
        //tipe data dan variable
        int N1, N2, Hasil;
        
        //input
        N1 = Integer.parseInt(Txt_N1.getText());
        N2 = Integer.parseInt(Txt_N2.getText());
        
        //proses
        Hasil = N1 + N2;
        
        //output
        Txt_Hasil.setText(String.valueOf(Hasil));
    }
    
    public void Kurang(){
        //tipe data dan variable
        int N1, N2, Hasil;
        
        //input
        N1 = Integer.parseInt(Txt_N1.getText());
        N2 = Integer.parseInt(Txt_N2.getText());
        
        //proses
        Hasil = N1 - N2;
        
        //output
        Txt_Hasil.setText(String.valueOf(Hasil));
    }
    
    public void Kali(){
        //tipe data dan variable
        int N1, N2, Hasil;
        
        //input
        N1 = Integer.parseInt(Txt_N1.getText());
        N2 = Integer.parseInt(Txt_N2.getText());
        
        //proses
        Hasil = N1 * N2;
        
        //output
        Txt_Hasil.setText(String.valueOf(Hasil));
    }
    
    public void Bagi(){
        //tipe data dan variable
        int N1, N2, Hasil;
        
        //input
        N1 = Integer.parseInt(Txt_N1.getText());
        N2 = Integer.parseInt(Txt_N2.getText());
        
        //proses
        Hasil = N1 / N2;
        
        //output
        Txt_Hasil.setText(String.valueOf(Hasil));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt_N2 = new javax.swing.JTextField();
        Btn_Kurang = new javax.swing.JButton();
        Btn_Kali = new javax.swing.JButton();
        Btn_Bagi = new javax.swing.JButton();
        Btn_Tambah = new javax.swing.JButton();
        Txt_Hasil = new javax.swing.JTextField();
        Txt_N1 = new javax.swing.JTextField();
        Btn_Hapus = new javax.swing.JButton();
        Btn_Keluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("K A L K U L A T O R");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("HASIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Nilai Ke-1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Nilai Ke-2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        getContentPane().add(Txt_N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, 30));

        Btn_Kurang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Kurang.setText("-");
        Btn_Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KurangActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 50, 40));

        Btn_Kali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Kali.setText("x");
        Btn_Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KaliActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 50, 40));

        Btn_Bagi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Bagi.setText("÷");
        Btn_Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BagiActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 50, 40));

        Btn_Tambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_Tambah.setText("+");
        Btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 50, 40));
        getContentPane().add(Txt_Hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 70, 30));
        getContentPane().add(Txt_N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, 30));

        Btn_Hapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Hapus.setForeground(new java.awt.Color(255, 51, 0));
        Btn_Hapus.setText("HAPUS");
        Btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 90, 30));

        Btn_Keluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Keluar.setForeground(new java.awt.Color(255, 51, 0));
        Btn_Keluar.setText("KELUAR");
        Btn_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 90, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, 80));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 370, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TambahActionPerformed
        // TODO add your handling code here:
        
        try{
            if(Txt_N1.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 1 kosong");
            Txt_N1.requestFocus();
            }else{
            if(Txt_N2.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 2 kosoong");
            Txt_N2.requestFocus();
            }else{
             //isi input, proses & output
            }
            }
            }catch(Exception e){
        }
        
        Tambah();
    }//GEN-LAST:event_Btn_TambahActionPerformed

    private void Btn_KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KurangActionPerformed
        // TODO add your handling code here:
        
        try{
            if(Txt_N1.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 1 kosong");
            Txt_N1.requestFocus();
            }else{
            if(Txt_N2.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 2 kosoong");
            Txt_N2.requestFocus();
            }else{
             //isi input, proses & output
            }
            }
            }catch(Exception e){
        }
        
        Kurang();
    }//GEN-LAST:event_Btn_KurangActionPerformed

    private void Btn_KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KaliActionPerformed
        // TODO add your handling code here:
        
        try{
            if(Txt_N1.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 1 kosong");
            Txt_N1.requestFocus();
            }else{
            if(Txt_N2.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 2 kosoong");
            Txt_N2.requestFocus();
            }else{
             //isi input, proses & output
            }
            }
            }catch(Exception e){
        }
        
        Kali();
    }//GEN-LAST:event_Btn_KaliActionPerformed

    private void Btn_BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BagiActionPerformed
        // TODO add your handling code here:
        
        try{
            if(Txt_N1.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 1 kosong");
            Txt_N1.requestFocus();
            }else{
            if(Txt_N2.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "data 2 kosoong");
            Txt_N2.requestFocus();
            }else{
             //isi input, proses & output
            }
            }
            }catch(Exception e){
        }
        
        Bagi();
    }//GEN-LAST:event_Btn_BagiActionPerformed

    private void Btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusActionPerformed
        // TODO add your handling code here:
        Txt_N1.setText("");
        Txt_N2.setText("");
        Txt_Hasil.setText("");
    }//GEN-LAST:event_Btn_HapusActionPerformed

    private void Btn_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Btn_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Bagi;
    private javax.swing.JButton Btn_Hapus;
    private javax.swing.JButton Btn_Kali;
    private javax.swing.JButton Btn_Keluar;
    private javax.swing.JButton Btn_Kurang;
    private javax.swing.JButton Btn_Tambah;
    private javax.swing.JTextField Txt_Hasil;
    private javax.swing.JTextField Txt_N1;
    private javax.swing.JTextField Txt_N2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
